config/routes.rb
Sociallogin::Application.routes.draw do  


	match 'users/:id/collects/new' => "collects#new" , :as => :collects
	match 'users/:id/collects/create' => "collects#create" , :as => :collect
#	match 'users/:id/collects/index' => "collects#index" , :as => :collects
	match 'users/:user_id/collects/:id' => "collects#show" , :as => :collect
	match 'users/:user_id/collects/:id/edit' => "collects#edit" , :as => :collect
	resources :users
#	resources :users do 
#		resources :collects do 
#			resources :pictures
#		end
#	end 


	root :to => 'welcome#index'
	get "welcome/index"
	get "welcome/home"
#	resources :albums

	
	match '/auth/:provider/callback', :to => 'session#create_social', :as => 'social_login'
  match 'logout' => 'session#destroy', :as => 'logout'
  	
  	
  	
end

app/models/collect.rb
class Collect < ActiveRecord::Base
belongs_to :user
has_many :pictures, :dependent => :destroy
accepts_nested_attributes_for :pictures , :allow_destroy => true
validates_presence_of :titulo
end

app/controllers/collects_controller.rb
class CollectsController < ApplicationController
  # GET /collects
  # GET /collects.json
  def index
    @collects = Collect.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @collects }
    end
  end

  # GET /collects/1
  # GET /collects/1.json
  def show
    @collect = Collect.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @collect }
    end
  end

  # GET /collects/new
  # GET /collects/new.json
  def new
  #  @picture = Picture.new
    @collect = Collect.new
   # 3.times { @collect.pictures.build }
  end

  # GET /collects/1/edit
  def edit
    @collect = Collect.find(params[:id])
  end

  # POST /collects
  # POST /collects.json
  def create
    @collect = Collect.new(params[:collect])
    @collect.user_id = params[:user_id]
    #@picture = Picture.new(params[:picture])
    #@picture.collect_id = @collect.id
    #@picture.save
    respond_to do |format|
      if @collect.save
        format.html { redirect_to '/welcome/home', :notice => 'Collect was successfully created.' }
        format.json { render :json => @collect, :status => :created, :location => @collect }
      else
        format.html { render :action => "new" }
        format.json { render :json => @collect.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /collects/1
  # PUT /collects/1.json
  def update
    @collect = Collect.find(params[:id])

    respond_to do |format|
      if @collect.update_attributes(params[:collect])
        format.html { redirect_to @collect, :notice => 'Collect was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @collect.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /collects/1
  # DELETE /collects/1.json
  def destroy
    @collect = Collect.find(params[:id])
    @collect.destroy

    respond_to do |format|
      format.html { redirect_to collects_url }
      format.json { head :ok }
    end
  end
end

app/helpers/collects_helper.rb
module CollectsHelper
end

app/views/collects/_form.html.erb
<%= semantic_form_for @collect  do |f| %>
	  <%= f.inputs do %>
	  <%= f.input :titulo, :label => "Que lugar recomendas!!!"%>
	  <% end %>
      <%= f.buttons do %>
      <%= f.commit_button %>
  <% end %>
<% end %>

app/views/collects/edit.html.erb
<h1>Editing collect</h1>

<%= render 'form' %>

<%= link_to 'Show', @collect %> |
<%= link_to 'Back', collects_path %>

app/views/collects/index.html.erb
<h1>Listing collects</h1>

<table>
  <tr>
    <th>Titulo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @collects.each do |collect| %>
  <tr>
    <td><%= collect.titulo %></td>
  </tr>
<% end %>
</table>

<br />

<a href = "/users/<%= current_user.id%>/collects/new"></a>

app/views/collects/new.html.erb
<div class = "linea"></div>
<h1 class = "ma">Crea tu album....</h1>

<div class= "center">


<h1>Nuevo Lugar</h1>

<%= render 'form' %>

</div>

app/views/collects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Titulo:</b>
  <%= @collect.titulo %>
  
</p>


<%= link_to 'Edit', edit_collect_path(@collect) %> |
<%= link_to 'Back', collects_path %>